language: python
python:
  - 3.6.1
before_install:
  - ls
install:
  - pip install numpy
  - pip install pandas
  - pip install -e git+https://github.com/cokelaer/bioservices#egg=master
  - pip install biopython

script:
  - python phytozomedler.py populus,fiveprime unsplicedTranscript mfo.FASTA
  - python intronitator.py mfo.FASTA -v
after_script: ls