language: python
python:
  - 3.6.1
before_install:
  - ls
install:
  - pip install numpy
  - pip install pandas
  - pip install -e git+https://https://github.com/cokelaer/bioservices#egg=master
  - pip install biopython
before_script:
  - ls
script: python phytozomedler.py arabidopsis,fiveprime unsplicedTranscript mfo.FASTA -t